print("          Wedding Vow          ")
print()

bride = input("bride's name: ")
groom = input("groom's name: ")
adjective = input("an adjective: ")
noun = input("a noun: ")
adjective_2 = input("an adjective: ")
almighty = input("The Creator's name: ")
plural_noun_1 = input("a plural noun: ")
plural_noun_2 = input("plural noun: ")
adjective_3 = input("adjective: ")
adjective_4 = input("adjective: ")
noun_2 = input("a noun: ")
verb = input("a verb: ")
unpleasant_noun = input("a unpleasant noun: ")
verb_2 = input("a verb: ")
verb_3 = input("a verb: ")
verb_4 = input("a verb: ")
adjective_5 = input("adjective: ")
period_of_time = input("period of time: ")

print("""


""")
print("I, " + bride + ", take you " + groom + ",")
print("to be my " + adjective + " husband,")
print("my constant " + noun + ", my " + adjective_2 + " partner,")
print("and my love from this day forward.")
print("in the presence of " + almighty + " our " + plural_noun_1 + ",")
print("and " + plural_noun_2 + ", I offer you my " + adjective_3 + " vow")
print("to be your " + adjective_4 + " " + noun_2 + " in sickness and")
print("in " + verb + ", good times, and in " + unpleasant_noun + " times.")
print("I promise to " + verb_2 + " you unconditionally and")
print("to always " + verb_3 + " and " + verb_4 + ",")
print("you have made me the " + adjective_5 + " person in the world,")
print("I look forward to the next " + period_of_time + " of our loves." )
